### ISSUE TITLE
ClassCastException: <packagename>.<PackagePrefix>Factory cannot be cast to <packagename>.<PackagePrefix>Factory

### ISSUE THREAD

**Issue by kyrillzotkin** [enterpriseDomain/ClassMaker#10]
java.lang.ClassCastException: some.SomeFactory cannot be cast to some.SomeFactory
	at some.SomeFactory.init(SomeFactory.java:38)
	at some.SomeFactory.<clinit>(SomeFactory.java:28)
	at some.SomePackage.<init>(SomePackage.java:119)
	at some.SomePackage.init(SomePackage.java:147)
	at some.SomePackage.<clinit>(SomePackage.java:57)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.enterprisedomain.classmaker.jobs.load.OSGiEPackageLoader.doLoad(OSGiEPackageLoader.java:157)
	at org.enterprisedomain.classmaker.jobs.load.OSGiEPackageLoader.access$0(OSGiEPackageLoader.java:142)
	at org.enterprisedomain.classmaker.jobs.load.OSGiEPackageLoader$1.bundleChanged(OSGiEPackageLoader.java:57)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:903)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by kyrillzotkin** [comment]
Made a ClassMakerPlant#produce(... boolean changeVersion) argument default to true.
