### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/emf/common/notify/Notification

### ISSUE THREAD

**Issue by kyrillzotkin** [enterpriseDomain/ClassMaker#17]
**Describe the bug**
java.lang.NoClassDefFoundError: org/eclipse/emf/common/notify/Notification at org.enterprisedomain.classmaker.tests.TestEnterpriseDomain.recreate(TestEnterpriseDomain.java:560)
Caused by: java.lang.ClassNotFoundException: org.eclipse.emf.common.notify.Notification cannot be found by dir_1.0.0.201909100914 at org.enterprisedomain.classmaker.tests.TestEnterpriseDomain.recreate(TestEnterpriseDomain.java:560)

**To Reproduce**
https://travis-ci.org/enterpriseDomain/ClassMaker/builds/583072688

**Expected behavior**
Shouldn't happen.

**Comment by kyrillzotkin** [comment]
Looks like explicitly specifying the dependencies did the trick. e86e5525c72259099857c3c8fdad643eeca7f1b0

**Comment by kyrillzotkin** [comment]
No, it appeared again.
